services:
    front-end:
        build:
            context: ./front-end
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            - NODE_ENV=production
            - VITE_PORT=5000
