name: Deploy to VPS

on:
    push:
        branches: main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up SSH
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.VPS_IP }}
                  username: root
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      # Navigate to the project directory
                      cd projects/vps-app-test

                      # Pull the latest code from the repository
                      git pull origin main

                      # Build and run Docker Compose
                      bash dev.sh
